Bd connection
IlyaBabich1994/BotMaster pull request #1
Opened 2024-12-16 20:18 UTC by IkitTheClaw

2024-12-18 17:43 UTC, IlyaBabich1994 requested changes

2024-12-24 01:34 UTC, IlyaBabich1994 requested changes

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/model/Bot.java
НИП:
Лишний пропуск

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/repository/ButtonRepository.java
> +
НИП: Лишний пропуск

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/repository/FilterRepository.java
> +
НИП: Лишний пропуск

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/BotServiceImpl.java
> +    @Autowired
Перенеси над конструктором.

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/ButtonServiceImpl.java
> +    @Autowired
Так же как в бот сервисе. Перенеси над конструктором.

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/BotServiceImpl.java
> +                () -> new RuntimeException("Bot not found")
Java не нул безопасна, лучше добавь проверку на нул и пустую строку
    if (token == null || token.isEmpty()) {
        throw new IllegalArgumentException("Token must not be null or empty");
    }

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/BotServiceImpl.java
> +        botRepository.save(bot);
Может сделать так, что бы он возвращал обратно бота?
Ну там если понадобится id нового объекта

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/ButtonServiceImpl.java
> +        buttonRepository.save(button);
В этих методах то же бы проводить валидацию данных
Хотя бы
    if (button == null) {
        throw new IllegalArgumentException("Button must not be null");
    }

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/ButtonServiceImpl.java
> +        buttonRepository.delete(button);
Сейчас глянул, удаление без проверки, теоретически может привести к проблемам 
Тоже стоит добавить валидацию
    if (button == null) {
        logger.error("Button is null");
        throw new IllegalArgumentException("Button must not be null");
    }
    if (!buttonRepository.existsById(button.getId())) {
        logger.error("Button with ID {} not found", button.getId());
        throw new IllegalArgumentException("Button not found");
    }

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/FilterServiceImpl.java
> +public class FilterServiceImpl implements FilterService{
Тоже самое что и у ButtonService

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/FilterServiceImpl.java
> +import java.util.List;
Стоит его на строчку выше перенести

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/UserService.java
> +    User findByTelegramId(Long telegramId);
Может все таки, что бы он возращал Optional?

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/java/com/example/demo/services/FilterService.java
> +    List<Filter> findAllByBotId(Long botId);
Посмотри
Что такие и как пользоваться пагинацией:
https://www.baeldung.com/spring-data-jpa-pagination-sorting
Дока на Page
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html
Референс на вовращаемые типы spring data
https://docs.spring.io/spring-data/jpa/reference/repositories/query-return-types-reference.html
Референс на pageable 
https://docs.spring.io/spring-data/rest/reference/paging-and-sorting.html


Page<Button> findAllByBotId(Long botId, Pageable pageable);

Лучше наверно так.
По сути вернет страничку с данными

2024-12-24 01:34 UTC, IlyaBabich1994 commented on src/main/resources/application.yml
> +    driver-class-name: org.postgresql.Driver
Добавь ddl
https://stackoverflow.com/questions/33323837/database-application-yml-for-spring-boot-from-applications-properties

Вот референс https://docs.spring.io/spring-boot/how-to/data-initialization.html

2024-12-30 22:23 UTC, IkitTheClaw reviewed
done?

2024-12-31 12:47 UTC, IlyaBabich1994 approved these changes

2024-12-31 13:21 UTC, IkitTheClaw commented
add models 
add services and implementations 
add interaction with database 
add config file for db
add mock tests

2024-12-31 14:28 UTC, IkitTheClaw commented
add connection and interaction with database

2024-12-31 14:29 UTC, merged